apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-L4CgEF1Vd49z
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::315069654700:role/RoboshopReader
      username: roboshop-reader
      groups:
        - roboshop-readers
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 512f49f3-fcbd-4a2e-8670-055c904a79ca