apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-reader-binding
  namespace: roboshop
subjects:
- kind: Group
  name: roboshop-readers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-reader
  apiGroup: rbac.authorization.k8s.io
